model: data/OpenSubtitles-v2016/actor_pretraining/a2c-2gpu-new/model_step_30000.pt
src: data/iwslt2014-test/iwslt14-test-src-processed.txt
output: data/iwslt2014-test/translation/A2C_actor_30000_new.txt
beam_size: 10
ban_unk_token: true