model: data/OpenSubtitles-v2016/actor_pretraining/ac-2gpu-new/model_step_100000.pt
src: data/iwslt2014-test/iwslt14-test-src-processed.txt
output: data/iwslt2014-test/translation/AC_actor_100000_new.txt
beam_size: 5
ban_unk_token: true