model: data/OpenSubtitles-v2016/actor_pretraining/ac-2gpu-new/model_step_100000.pt
src: data/OpenSubtitles-v2016/randomised_test_set_5k/src.txt
output: data/OpenSubtitles-v2016/randomised_test_set_5k/AC_actor_100000_new.txt
beam_size: 10
ban_unk_token: true