model: data/OpenSubtitles-v2016/actor_pretraining/a2c-2gpu-new/model_step_100000.pt
src: data/OpenSubtitles-v2016/randomised_test_set_5k/src.txt
output: data/OpenSubtitles-v2016/randomised_test_set_5k/A2C_actor_100000_new.txt
beam_size: 5
ban_unk_token: true