model: data/OpenSubtitles-v2016/joint_training/a2c-alt/model_step_145600.pt
src: data/iwslt2014-test/iwslt14-test-src-processed.txt
output: data/iwslt2014-test/translation/A2C_145600_topk.txt
beam_size: 10
ban_unk_token: true
random_sampling_topk: 10
random_sampling_temp: 0.4