model: data/OpenSubtitles-v2016/actor_pretraining/a2c/model_step_100000.pt
src: data/iwslt2014-test/iwslt14-test-src-processed.txt
output: data/iwslt2014-test/translation/A2C_actor_100000_topk.txt
beam_size: 10
ban_unk_token: true
random_sampling_topk: 10
random_sampling_temp: 0.4