save_data: data/multi30k-dataset

## Where the vocab(s) will be written
src_vocab: data/multi30k-dataset/data/task1/tok/en.vocab.src

tgt_vocab: data/multi30k-dataset/data/task1/tok/fr.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: True

# Corpus opts:
data:
    mult30k:
        path_src: data/multi30k-dataset/data/task1/tok/train.lc.norm.tok.en
        path_tgt: data/multi30k-dataset/data/task1/tok/train.lc.norm.tok.fr
        transforms: []
#        transforms: [sentencepiece]
    valid:
        path_src: data/multi30k-dataset/data/task1/tok/val.lc.norm.tok.en
        path_tgt: data/multi30k-dataset/data/task1/tok/val.lc.norm.tok.fr
        transforms: []
#        transforms: [sentencepiece]


# # Model training parameters

# General opts
save_model: data/multi30k-models/joint_training/acq-1gpu-multi30k-surf_temp/model
train_from: data/multi30k-models/critic_pretraining/acq-1gpu-multi30k-surf_topp/model_step_800.pt
reset_optim: "all"
keep_checkpoint: 50
save_checkpoint_steps: 50
average_decay: 0.0005
seed: 1234
report_every: 1
train_steps: 10000
valid_steps: 10000

# Batching
master_port: 1234
queue_size: 1024
bucket_size: 32768
pool_factor: 8192
world_size: 1
gpu_ranks: [0]
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 4096
batch_size_multiple: 1
max_generator_batches: 0
accum_count: [3]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 6000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
model_task: acse
train_mode: ac
policy_strategy: [categorical, categorical, categorical]
policy_topk_sampling: [500,500,500]
policy_sampling_temperature: [0.9,1.0,1.0]
policy_topp_sampling: [1.0,1.0,1.0]
discount_factor: 0.99
multi_step: 5
unsuper_reward: true
w_fluency: 1
w_tlss: 0
w_slss: 1
norm_unsuper_reward: true
lambda_var: 0.25
use_target_network: true
target_network_update_period: 500
encoder_type: transformer
decoder_type: transformer
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
position_encoding: true